variable "COMPONENT" {}
variable "APP_VERSION" {}
variable "ENV" {}
variable "PRIVATE_SUBNET_ID" {}
variable "AGS_DESIRED" {}
variable "AGS_MAX" {}
variable "AGS_MIN" {}
variable "PROMETHEUS_IP" {}
variable "WORKSTATION_IP" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "SSH_PORT" {}
variable "PORT" {}
variable "INSTANCE_TYPE" {}
variable "VPC_ID" {}